# site settings
title: Newtechco Group
subtitle:
email: info.newtechco@gmail.com
description: Newtechco Group's website
baseurl: ""
url: 
author:
street_address: 44 Ly Thuong Kiet
city: Hanoi
country: Vietnam
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

defaults:
    -
     scope:
         path: ""
     values:
         lang: vi
         lang-url: ""
    -
     scope:
         path: en
     values:
         lang: en
         lang-url: "/en"

# Translation
transl:
    home:
        vi: "Trang chá»§"
        en: "Home"
    group:
        vi: "Táº­p Ä‘oÃ n"
        en: "Group"
    team:
        vi: "Äá»™i ngÅ©"
        en: "Team"
    associate:
        vi: "CÃ´ng ty thÃ nh viÃªn"
        en: "Associate Companies"
    partner:
        vi: "Äá»‘i tÃ¡c"
        en: "Partners"
    career:
        vi: "Tuyá»ƒn dá»¥ng"
        en: "Careers"
    latest:
        vi: "Tin tá»©c"
        en: "Latest"
    contact:
        vi: "LiÃªn há»‡"
        en: "Contact"
    lang:
	    vi: "ğŸ‡»ğŸ‡³"
	    en: "ğŸ‡¬ğŸ‡§"

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub:
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
